# Generated by Django 5.0.6 on 2024-10-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Highest'), (2, 'High'), (3, 'Medium'), (4, 'Low'), (5, 'Lowest')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='states',
            field=models.IntegerField(choices=[(1, 'To Do'), (2, 'In Progress'), (3, 'Completed'), (4, 'On Hold'), (5, 'Cancelled')]),
        ),
    ]
