# Generated by Django 5.0.6 on 2024-10-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='emoji',
            field=models.CharField(blank=True, default='📑', max_length=10),
        ),
    ]
