# Generated by Django 5.0.6 on 2024-10-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Upload an avatar image for the employee.', null=True, upload_to='avatars/'),
        ),
    ]
